### ISSUE TITLE
What about support for treesitter?

### ISSUE THREAD

**Issue by cjnucette** [ghifarit53/daycula-vim#10]
It is getting better and better https://github.com/nvim-treesitter/nvim-treesitter

**Comment by ghifarit53** [comment]
Hi @cjnucette! Thanks for the feature request

First, i'm not really sure what nvim-treesitter is (from skimming their readme, looks like it's a highlighting plugin (and much more), am I right?)

Second, I'm afraid I can't do that as for now.
The reason is this colorscheme uses [sainnhe](https://github.com/sainnhe)'s colorscheme as the base. I change the color definition in the code and adding some small fix. The code itself is really huge and (just my guess) It'll take sometime (even longer) to understand some of the parts and adding some changes. Writing this theme from scratch looks easier

**Comment by ghifarit53** [comment]
Closing for now
